name: Deploy

on:
    pull_request:
      # Deploys to Render after closing/merging code from the PR to main
      types: closed
      branches:
        - main
       
jobs:
    ci:
      name: Deploy To Render
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v1

        - name: Install dependencies
          run: npm install

        - name: Deploy
          if: github.ref == 'refs/heads/main'
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$DEPLOY_URL"
  