# Name of workflow
name: Cypress Tests

# Trigger workflow on all pull requests
on:
    pull_request:
        branches:
            - develop
            - staging

# Jobs to carry out
jobs:
    test:
        # Operating system to run job on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x, 21.x]

        # Steps in job
        steps:
            # Get code from repo
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Use Node.js 21.x
              uses: actions/setup-node@v1
              with:
                  node-version: 21.x

            # Install dependencies
            - name: 🧰 Install Deps
              run: npm install

            # Run lint
            - name: Run Lint
              run: npm run lint

            - name: Cypress
              uses: cypress-io/github-action@v6
              with:
                  build: npm run build
                  start: npm run start
                  component: true

            # # Run build
            # - name: Run Build
            #   run: npm run build

            # # Run start
            # - name: Run Start
            #   run: npm run start

            # # Run tests
            # - name: Run Cypress Tests
            #   run: npm run test
