# Name of workflow
name: Cypress Tests

# Trigger workflow on all pull requests
on:
    pull_request:
        branches:
            - develop
            - staging

# Jobs to carry out
jobs:
    cypress-run:
        # Operating system to run job on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x, 21.x]

        # Steps in job
        steps:
            # Get code from repo
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.node-version}}

            # Install dependencies
            - name: 🧰 Install Deps
              run: npm install

            # Run Cypress component tests (testing for 3 node versions?)
            - name: Cypress
              uses: cypress-io/github-action@v6
              with:
                  build: npm run build
                  start: npm run start
                  component: true
